const data = [
  {
    image: "kitchen",
    name: "Kitchen Utensils",
    grossPrice: "40",
    salePrice: "36",
    percentDiscount: 10,
    rating: 3.9,
    reviewNumber: 16,
  },
  {
    image: "samsung",
    name: "Samsung RS65R5441M9..",
    grossPrice: "",
    salePrice: "1200",
    percentDiscount: "",
    rating: 5.0,
    reviewNumber: 20,
  },
  {
    image: "nordic",
    name: "NordicTrack T Series Tre..",
    grossPrice: "950",
    salePrice: "855",
    percentDiscount: 10,
    rating: 4.0,
    reviewNumber: 5,
  },
  {
    image: "sweater",
    name: "Yellow Sweater Designe..",
    grossPrice: "",
    salePrice: "10",
    percentDiscount: "",
    rating: 4.0,
    reviewNumber: 20,
  },
  {
    image: "suit",
    name: "Fitted Italian Suit - Grey",
    grossPrice: "60",
    salePrice: "48",
    percentDiscount: "20",
    rating: 4.4,
    reviewNumber: 12,
  },
  {
    image: "hobby",
    name: "Hhobby Stars 61 Pcs",
    grossPrice: "64",
    salePrice: "40",
    percentDiscount: "32",
    rating: 4.0,
    reviewNumber: 23,
  },
];

export default data;
